<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsTestProject>true</IsTestProject><IsPackable>false</IsPackable><UseAppHost>false</UseAppHost></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Mint.Sales.WorkerService.OrderProcessing.Domain/Mint.Sales.WorkerService.OrderProcessing.Domain.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
